### ISSUE TITLE
Build script tries to link 32 bit libraries on 64 bit only system

### ISSUE THREAD

**Issue by hollaho** [OpenVnmrJ/ovjTools#19] opened 2017-01-12 20:04 UTC
The readme states that 64 bit build needs to be tested, so I went ahead. But the build script hardcodes 32 bit libraries despite running in a 64 bit only x86_64 environment:

gcc -o src/bin/pulsechild -m32 -Wl,-rpath,/vnmr/lib src/bin/pulsechild.o src/bin/pulsechild_mf.o -L/usr/X11R6/lib -L/usr/lib32/i386-linux-gnu -lXm -lXt -lX11 -lm
gcc -o src/bin/safecp -m32 src/bin/safecp.o
src/bin/vnmrio.h: In function 'add_phase3d':
src/bin/vnmrio.h:4058:17: warning: variable 'ph' set but not used [-Wunused-but-set-variable]
   int     i, j, ph;
                 ^
Copy("/usr/src/openvnmrjbuild/OpenVnmrJ/src/admin/../../../options/code", "/usr/src/openvnmrjbuild/OpenVnmrJ/src/admin/VnmrAdmin.jar")
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../libXm.so when searching for -lXm
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libXm.so when searching for -lXm
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lXm
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../libXt.so when searching for -lXt
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libXt.so when searching for -lXt
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lXt
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../libX11.so when searching for -lX11
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../../../../x86_64-pcsrc/bin/sch2fid.c: In function 'main':
-linuxsrc/bin/sch2fid.c:34:16: warning: variable 'f1z' set but not used [-Wunused-but-set-variable]
     float f1d, f1z;
                ^
-gnu/bin/ld: skipping incompatible /usr/lib/libX11.so when searching for -lX11
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/../src/bin/sch2fid.c:34:11: warning: variable 'f1d' set but not used [-Wunused-but-set-variable]
     float f1d, f1z;
           ^
../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lX11
collect2: error: ld returned 1 exit status

----

So how can I configure / change this to compile 64 bit?

**Comment by DanIverson** [comment] 2017-01-13 19:26
The comment about testing a 64-bit build is perhaps a little misleading in that it does not convey the scope of this task. This will be a fairly large undertaking. As you noted, it will involve changing the -m32 options to -m64. There are a number of include files that interchangeably use int and long and some programs that assume pointers are the size of an int. To fully test this, one will also need access to Mercury, Inova, and DDR style spectrometers.

**Comment by tesch1** [comment] 2017-04-25 15:35
This is open, might be better to collect all issues on the OpenVnmrJ/OpenVnmrJ repo: https://github.com/OpenVnmrJ/OpenVnmrJ/issues/20

**Comment by tesch1** [comment] 2017-04-25 16:12
@DanIverson -- that's an interesting point... does *anyone* have access to Mercury, Inova **and** DDR spectrometers?!?

**Comment by mstrain** [comment] 2017-04-25 17:42
I have Inova and Mercury spectrometers (in production, running OpenVnmrJ)
but nothing newer.

--Mike Strain
University of Oregon

**Comment by DanIverson** [comment] 2017-04-27 21:08
Duplicate of OpenVnmrJ/OpenVnmrJ#20

**Closed by DanIverson** 2017-04-27 21:08 UTC
